<%@ page language="java" session="true"%>
<%@ page import="java.math.*" %>
<%@ page import="oracle.jdbc.driver.*" %>
<%@ page contentType="text/html" %>
<%@ page import="java.util.*" %>
<%@ page import="java.io.* "%>
<%@ page import="java.lang.*" %>
<%@ page import="java.sql.*" %>
<%@ page import="java.text.*" %>
<%@ page import="java.util.Date" %>
<%@ page import="java.io.*" %>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>NFL Hospital</title>
<script language="JavaScript1.2">
function alert()
{
}
 </script>

</head>

<body background="/hosp1/Stationery/Clear%20Day%20Bkgrd.jpg">

<%@include file="/navbar.jsp" %>


  <div align="right">
  <table border="0" width="92%">
    <tr>
      <td width="31%"><!--** START NAVSTUDIO MENU TAGS (346080) **-->
<div id="vqp_about" style="position:absolute;visibility:hidden;">
  <p align="left" style="margin-left: -30">****JavaScript based drop down DHTML menu generated by NavStudio. (OpenCube Inc. - http://www.opencube.com)****</div>
<script language="JavaScript" vqptag="doc_level_settings" vqp_datafile0="menu.js" vqp_uid0=346080>cdd__codebase = "menu/";cdd__codebase346080 = "menu/";</script>
<script language="JavaScript" vqptag="datafile" src="menu/menu.js"></script><script vqptag="placement" vqp_menuid="346080" language="JavaScript">create_menu(346080)</script>
<!--** END NAVSTUDIO MENU TAGS **--></td>

      <td width="69%" background="../logo/nflhos.gif">&nbsp;
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        &nbsp;
  </table>

  </div>
  <p style="margin-bottom: -10">&nbsp;</p>
<hr>


</body>

</html>